# Generated by Django 3.0.5 on 2021-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
